# 2. 矩阵和向量的乘法
## 引言
点积（内积）是线性代数中的一个重要概念，它在机器学习和数据科学中扮演着关键角色。我们将探讨这一运算的一些性质。随后，我们将对矩阵与线性方程组之间的联系进行一些直观的解释。

## 2.1 矩阵和向量的乘法  
标准的方法不是将一个矩阵的每个元素与另一个矩阵的每个元素相乘（称为逐元素乘积），而是通过行列之间的乘积之和来计算。矩阵乘积也被称为点积，其计算方式如下：  
$$\begin{bmatrix}A&B\\C&D\\E&F\end{bmatrix}\times\begin{bmatrix}G\\H\end{bmatrix}=\begin{bmatrix}A\times G+B\times H\\C\times G+D\times H\\E\times G+F\times H\end{bmatrix}$$  

第一个矩阵的列数必须等于第二个矩阵的行数。如果第一个矩阵的尺寸是$(m×n)$，则第二个矩阵必须是$(n×x)$的形状。结果矩阵将是$(m×x)$的形状。

### 例1
![例1](../pics/Snipaste_2024-11-21_23-14-13.png)


In [4]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [6]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

### 例2
![例2](../pics/Snipaste_2024-11-21_23-37-07.png)

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [9]:
C = A.dot(B)
C

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])