# 1. 标量、向量、矩阵和张量
## 1.1 标量、向量、矩阵和张量
![标量、向量、矩阵和张量](../pics/Snipaste_2024-11-20_22-35-25.png)

In [ ]:
import numpy as np

# 创建数组
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [ ]:
# 创建矩阵
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## 1.2 维度 Shape（秩 Rank）

In [ ]:
A.shape

(3, 2)

In [ ]:
x.shape

(4,)

In [ ]:
len(x)

4

## 1.2 矩阵转置 Transposition
![矩阵转置](../pics/Snipaste_2024-11-20_22-52-54.png)
![矩阵转置2](../pics/Snipaste_2024-11-21_22-29-44.png)

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
A_t_t = A.T.T
A_t_t

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
A.shape

(3, 2)

In [ ]:
A_t.shape

(2, 3)

## 1.3 矩阵加法 Addition
![矩阵加法](../pics/Snipaste_2024-11-20_23-09-05.png)

#### 1.3.1 矩阵A + 矩阵B
  必须满足：
- 矩阵A和矩阵B的维度必须相同
- 矩阵A和矩阵B的元素个数必须相同

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2, 5], [7, 4], [4, 3]])
# Add matrices A and B
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

#### 1.3.2 标量 + 矩阵
![标量+矩阵](../pics/Snipaste_2024-11-20_23-35-49.png)

In [ ]:
# Exemple: Add 4 to the matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])
C = A+4
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## 1.4 广播
Numpy可以处理不同形状数组之间的操作。较小的数组将被扩展以匹配较大数组的形状。其优势在于这是在底层完成的（就像Numpy中的任何向量化操作一样）。
![广播](../pics/Snipaste_2024-11-20_23-38-17.png)